allow_anonymous false

listener 8883
protocol mqtt

cafile /certs/ca.crt
certfile /certs/mosquitto.crt
keyfile /certs/mosquitto.key

require_certificate true
use_identity_as_username true

persistence false
log_type all
